"""The siren matcher against real @air_alert_ua posts (#23).

`tests/fixtures/real-air_alert_ua-2026-08.jsonl` is 35 posts captured from the
channel's public web preview (t.me/s/air_alert_ua) on 2026-08-31 -- real ids, real
UTC timestamps, text verbatim. Every other siren fixture in `tests/fixtures/` is
named `synthetic-*` and was written from an assumption about the format.

The window is two complete Kyiv-city cycles (333536-333546 and 333562-333580,
27-28 Aug) plus five posts of the shapes the channel uses that are *not* an air-raid
alert at all. `EXPECTED` below is hand-labelled from what each post says, never
generated by running the matcher.

What the capture settled: the region arrives in the **message text**, twice -- in
prose (`Повітряна тривога в м. Київ`) and again as a trailing hashtag (`#м_Київ`).
Hashtags are text entities, i.e. offsets into the same string Telethon hands over as
`message.message`, so the matcher reads the right field.
"""
import json

import pytest

from home_alert import events
from harness import FIXTURES

FIXTURE = "real-air_alert_ua-2026-08"

# id -> what a human reading the post says it means for the siren in м. Київ.
EXPECTED = {
    331172: "not-siren",   # Загроза ударних БпЛА в м. Запоріжжя -- an advisory, no alert
    331332: "not-siren",   # БЕЗКОШТОВНА ЕВАКУАЦІЯ -- a public-service notice
    331375: "not-siren",   # УВАГА !!! Загроза КАБів #Пологівський_район
    331508: "not-siren",   # Відбій загрози застосування КАБ -- an all-clear, but not of a siren
    332018: "not-siren",   # Відбій ... "тривога ще триває у:" -- says тривога, is not one
    333536: "on",          # Повітряна тривога в м. Київ
    333537: "not-kyiv",    # Одеський район
    333538: "not-kyiv",    # Обухівський район
    333539: "not-kyiv",    # Нікопольський район
    333540: "not-kyiv",    # Броварський район, відбій
    333541: "not-kyiv",    # Бориспільський район, відбій
    333542: "not-kyiv",    # Обухівський район, відбій
    333543: "not-kyiv",    # Бучанський район, відбій
    333544: "not-kyiv",    # Чернігівський район, відбій
    333545: "not-kyiv",    # Вишгородський район, відбій
    333546: "off",         # Відбій тривоги в м. Київ
    333562: "on",          # Повітряна тривога в м. Київ
    333563: "not-kyiv",    # Бучанський район
    333564: "not-kyiv",    # Обухівський район
    333565: "not-kyiv",    # Фастівський район
    333566: "not-kyiv",    # Миргородський район, відбій
    333567: "not-kyiv",    # Лубенський район, відбій
    333568: "not-kyiv",    # Черкаський район, відбій
    333569: "not-kyiv",    # Золотоніський район, відбій
    333570: "not-kyiv",    # Херсонський район
    333571: "not-kyiv",    # Новомосковський район, відбій
    333572: "not-kyiv",    # Красноградський район, відбій
    333573: "not-kyiv",    # Павлоградський район, відбій
    333574: "not-kyiv",    # Лозівський район, відбій
    333575: "not-kyiv",    # Нікопольський район, відбій
    333576: "not-kyiv",    # Охтирський район, відбій
    333577: "not-kyiv",    # Конотопський район, відбій
    333578: "not-kyiv",    # Обухівський район, відбій
    333579: "not-kyiv",    # Фастівський район, відбій
    333580: "off",         # Відбій тривоги в м. Київ
}

POSTS = [json.loads(line) for line
         in (FIXTURES / f"{FIXTURE}.jsonl").read_text(encoding="utf-8").splitlines()
         if line.strip()]


def test_every_captured_post_is_labelled():
    """A post nobody has read is a post nobody has checked."""
    assert sorted(p["id"] for p in POSTS) == sorted(EXPECTED)


@pytest.mark.parametrize("post", POSTS, ids=lambda p: str(p["id"]))
def test_the_matcher_reads_a_real_post_the_way_a_human_does(post):
    assert events.siren_verdict(post["text"]) == EXPECTED[post["id"]]


def test_all_four_verdicts_are_exercised_by_real_posts():
    assert set(EXPECTED.values()) == {"on", "off", "not-kyiv", "not-siren"}


def test_the_prose_form_matches_without_the_hashtag():
    """The regression #23 found: `м[._ ]?київ` allowed one separator, so it matched
    `#м_Київ` but not the prose `м. Київ` -- dot *and* space. Every real post carries
    both, so the miss was invisible; the day the channel drops the hashtag it would
    not have been. The prose alone must be enough."""
    assert events.siren_verdict("🔴 07:29 Повітряна тривога в м. Київ") == "on"
    assert events.siren_verdict("🟢 07:18 Відбій тривоги в м. Київ.") == "off"


def test_a_word_ending_in_m_before_kyiv_is_not_the_city():
    """`\\b` guards the loosened separator: `...ським Київ` is not `м. Київ`."""
    assert events.siren_verdict("Повітряна тривога в Броварським Київська") == "not-kyiv"
